trigger:
  batch: true
  branches:
    include:
      - pcc

pool: Rabo-Build-Azure-Linux-Preview

jobs:
  - job: Build
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/pcc')
    steps:
      - checkout: self
        persistCredentials: true
      - task: Maven@3
        inputs:
          mavenPomFile: pom.xml
          options: '-s .mvn/settings.xml'
          goals: 'package'
          publishJUnitResults: true
          jdkVersionOption: 1.8
          testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - job: SetLastCommiter
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/pcc')
    steps:
      - script: |
          UserName=`git log -1 --pretty=format:'%an'`
          echo "##vso[task.setvariable variable=UserName;isOutput=true]$UserName"
        name: setUserNameStep
        displayName: Set last commiter username

  - job: Release
    dependsOn: SetLastCommiter
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/pcc'), ne(dependencies.SetLastCommiter.outputs['setUserNameStep.UserName'], 'Azure pipeline'))
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: 'git config user.email "azure-pipeline@rabobank.nl"'
        displayName: Set git user email

      - script: 'git config user.name "Azure pipeline"'
        displayName: Set git user name

      - bash: 'git branch -D release || true'
        displayName: Remove release branch

      - bash: 'git switch -c release'
        displayName: Switch to release branch

      - task: Maven@3
        displayName: Maven release clean, prepare, perform
        inputs:
          mavenPomFile: pom.xml
          options: '--batch-mode -s .mvn/settings.xml -DlocalCheckout=true -DpushChanges=false -DnexusUser=$(Nexus.User) -DnexusPassword=$(Nexus.Password)'
          goals: 'release:clean release:prepare release:perform'
          publishJUnitResults: false
          jdkVersionOption: 1.8

      - bash: 'git fetch --all && git push origin release:pcc --tags'
        displayName: Push to pcc

      - bash: 'git checkout pcc && git branch -D release'
        displayName: Remove release branch