trigger:
    - master

pool: Rabo-Build-Azure-Linux

variables:
  nexus.snapshots.repository: 'https://maven.rabobank.nl/nexus/content/repositories/gict-snapshots'
  nexus.releases.repository: 'https://maven.rabobank.nl/nexus/content/repositories/gict-release'

steps:
  - script: git config user.email "azure-pipeline@rabobank.nl"
    displayName: Set git user email

  - script: git config user.name "Azure pipeline"
    displayName: Set git user name

  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleWrapperFile: 'gradlew'
      options: '-build-file pcc.gradle'
      publishJUnitResults: false
      jdkVersionOption: 1.8
      tasks: 'publish'